In [275]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.linear_model import LinearRegression
import matplotlib
from replaceNA import *

In [195]:
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [325]:
df = pd.read_csv('Weather1.csv', sep=';')

In [326]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindSpeed9am,Humidity9am,Pressure9am,Pressure3pm
0,01.12.2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,20.0,71.0,1007.7,1007.1
1,02.12.2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,4.0,44.0,1010.6,1007.8
2,03.12.2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,19.0,38.0,1007.6,1008.7
3,04.12.2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,11.0,45.0,1017.6,1012.8
4,05.12.2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,7.0,82.0,1010.8,1006.0

In [340]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4109 entries, 0 to 4998
Data columns (total 12 columns):
Date             4109 non-null object
Location         4109 non-null object
MinTemp          4109 non-null float64
MaxTemp          4109 non-null float64
Rainfall         4109 non-null float64
WindGustDir      4109 non-null object
WindGustSpeed    4109 non-null float64
WindDir9am       4109 non-null object
WindSpeed9am     4109 non-null float64
Humidity9am      4109 non-null float64
Pressure9am      4109 non-null float64
Pressure3pm      4109 non-null float64
dtypes: float64(8), object(4)
memory usage: 417.3+ KB

In [341]:
df.describe()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,Humidity9am,Pressure9am,Pressure3pm
count,4109.000000,4109.000000,4109.000000,4109.000000,4109.000000,4109.000000,4109.000000,4109.000000
mean,10.602239,76.193163,0.679824,34.750304,9.818691,72.921392,1017.810246,1015.205159
std,5.692267,23.257720,2.111732,13.097714,6.300182,17.149165,7.038245,6.899726
min,-2.800000,22.056931,0.000000,7.000000,2.000000,18.000000,989.800000,982.900000
25%,6.000000,57.737262,0.000000,26.000000,6.000000,60.000000,1013.000000,1010.400000
50%,10.400000,74.279960,0.000000,33.000000,7.000000,73.000000,1017.900000,1015.200000
75%,15.200000,93.093225,0.184346,43.000000,13.000000,86.000000,1022.500000,1019.900000
max,28.300000,148.559920,35.640244,107.000000,48.000000,100.000000,1039.900000,1036.800000

In [329]:
#удаляем столбцы, где отсутствуют все значения
df = dropNA(df, axis = 'columns', how = 'all')
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindSpeed9am,Humidity9am,Pressure9am,Pressure3pm
0,01.12.2008,Albury,13.4,22.9,0.6,W,44.0,W,20.0,71.0,1007.7,1007.1
1,02.12.2008,Albury,7.4,25.1,0.0,WNW,44.0,NNW,4.0,44.0,1010.6,1007.8
2,03.12.2008,Albury,12.9,25.7,0.0,WSW,46.0,W,19.0,38.0,1007.6,1008.7
3,04.12.2008,Albury,9.2,28.0,0.0,NE,24.0,SE,11.0,45.0,1017.6,1012.8
4,05.12.2008,Albury,17.5,32.3,1.0,W,41.0,ENE,7.0,82.0,1010.8,1006.0

In [332]:
df
#df = replace(df, ['MinTemp'],  value = 'mean')
#df = dropNA(df, axis = 'rows', how='any')

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindSpeed9am,Humidity9am,Pressure9am,Pressure3pm
0,01.12.2008,Albury,13.4,74.279960,0.184346,W,44.0,W,20.0,71.0,1007.7,1007.1
1,02.12.2008,Albury,7.4,81.416026,0.000000,WNW,44.0,NNW,4.0,44.0,1010.6,1007.8
2,03.12.2008,Albury,12.9,83.362226,0.000000,WSW,46.0,W,19.0,38.0,1007.6,1008.7
3,04.12.2008,Albury,9.2,90.822659,0.000000,NE,24.0,SE,11.0,45.0,1017.6,1012.8
4,05.12.2008,Albury,17.5,104.770424,0.307243,W,41.0,ENE,7.0,82.0,1010.8,1006.0
5,06.12.2008,Albury,14.6,96.336892,0.061449,WNW,56.0,W,19.0,55.0,1009.2,1005.4
6,07.12.2008,Albury,14.3,81.091660,0.000000,W,50.0,SW,20.0,49.0,1009.6,1008.2
7,08.12.2008,Albury,7.7,86.605892,0.000000,W,35.0,SSE,6.0,48.0,1013.4,1010.1
8,09.12.2008,Albury,9.7,103.472958,0.000000,NNW,80.0,SE,7.0,42.0,1008.9,1003.6
9,10.12.2008,Albury,13.1,97.634358,0.430141,W,28.0,S,15.0,58.0,1007.0,1005.7
10,11.12.2008,Albury,13.4,98.607458,0.000000,N,30.0,SSE,17.0,48.0,1011.8,1008.7
11,12.12.2008,Albury,15.9,70.387560,0.675936,NNE,31.0,NE,15.0,89.0,1010.5,1004.2
12,13.12.2008,Albury,15.9,60.332195,4.792998,W,61.0,NNW,28.0,76.0,994.3,993.0
13,14.12.2008,Albury,12.6,68.116994,1.106077,SW,44.0,W,24.0,65.0,1001.2,1001.8
14,16.12.2008,Albury,9.8,89.849559,NaN,WNW,50.0,NaN,NaN,50.0,1013.4,1010.3
15,17.12.2008,Albury,14.1,67.792627,0.000000,ENE,22.0,SSW,11.0,69.0,1012.2,1010.4
16,18.12.2008,Albury,13.5,74.279960,5.161690,W,63.0,N,6.0,80.0,1005.8,1002.2
17,19.12.2008,Albury,11.2,72.982494,3.256781,SSE,43.0,WSW,24.0,47.0,1009.4,1009.7
18,20.12.2008,Albury,9.8,83.037859,0.000000,SSE,26.0,SE,17.0,45.0,1019.2,1017.1
19,21.12.2008,Albury,11.5,95.039425,0.000000,S,24.0,SE,9.0,56.0,1019.3,1014.8
20,22.12.2008,Albury,17.1,107.040991,0.000000,NE,43.0,NE,17.0,38.0,1013.6,1008.1
21,23.12.2008,Albury,20.5,103.148591,0.000000,WNW,41.0,W,19.0,54.0,1007.8,1005.7
22,24.12.2008,Albury,15.3,100.229291,0.000000,N,33.0,ESE,6.0,55.0,1011.0,1008.2
23,25.12.2008,Albury,12.6,105.094791,0.000000,W,43.0,E,4.0,49.0,1012.9,1010.1
24,26.12.2008,Albury,16.2,109.960290,0.000000,WSW,35.0,SE,9.0,45.0,1010.9,1007.6
25,27.12.2008,Albury,16.9,107.040991,0.000000,WSW,57.0,NaN,0.0,41.0,1006.8,1003.6
26,28.12.2008,Albury,20.1,106.067891,0.000000,WNW,48.0,N,13.0,56.0,1005.2,1001.7
27,29.12.2008,Albury,19.7,88.227726,0.000000,WNW,46.0,NW,19.0,49.0,1004.8,1004.2
28,30.12.2008,Albury,12.5,78.496726,0.368692,WNW,50.0,WSW,11.0,78.0,1005.6,1003.4
29,31.12.2008,Albury,12.0,79.145460,0.245795,W,39.0,WNW,17.0,48.0,1006.1,1005.1
...,...,...,...,...,...,...,...,...,...,...,...,...
4969,03.10.2014,BadgerysCreek,7.7,73.631227,0.000000,E,33.0,NW,2.0,53.0,1021.0,1018.6
4970,04.10.2014,BadgerysCreek,12.6,84.010959,0.000000,N,26.0,N,13.0,72.0,1020.2,1014.7
4971,05.10.2014,BadgerysCreek,8.2,108.014090,0.000000,ESE,31.0,N,4.0,86.0,1016.2,1012.5
4972,06.10.2014,BadgerysCreek,15.7,103.148591,0.000000,E,26.0,N,4.0,73.0,1019.2,1011.3
4973,08.10.2014,BadgerysCreek,11.6,70.387560,NaN,NaN,NaN,S,11.0,74.0,1018.7,1017.2
4974,09.10.2014,BadgerysCreek,13.1,75.577427,0.000000,ENE,31.0,NW,4.0,65.0,1023.2,1019.2
4975,10.10.2014,BadgerysCreek,8.7,85.308426,0.000000,E,30.0,S,4.0,77.0,1019.5,1014.3
4976,11.10.2014,BadgerysCreek,9.5,99.904925,0.000000,ENE,33.0,NaN,0.0,70.0,1016.8,1013.1
4977,12.10.2014,BadgerysCreek,8.8,104.446057,0.000000,ENE,37.0,SSW,2.0,65.0,1017.5,1011.7
4978,13.10.2014,BadgerysCreek,11.0,81.416026,0.000000,NW,50.0,NNE,4.0,68.0,1007.6,1004.7
4979,14.10.2014,BadgerysCreek,9.9,59.359095,4.055614,SSW,52.0,W,9.0,51.0,1009.0,1009.3
4980,15.10.2014,BadgerysCreek,10.1,57.088528,10.630624,SW,57.0,SW,28.0,70.0,1013.0,1013.7
4981,16.10.2014,BadgerysCreek,4.8,77.523627,0.307243,ESE,31.0,NaN,0.0,71.0,1018.2,1015.1
4982,17.10.2014,BadgerysCreek,8.1,66.170794,0.000000,SE,31.0,SSW,13.0,72.0,1024.8,1024.4
4983,18.10.2014,BadgerysCreek,8.4,71.036294,0.000000,E,30.0,SW,7.0,60.0,1029.9,1026.6
4984,19.10.2014,BadgerysCreek,7.8,90.498292,0.000000,NNW,22.0,S,2.0,71.0,1027.5,1021.9
4985,20.10.2014,BadgerysCreek,12.6,60.656561,0.000000,SSE,37.0,S,20.0,67.0,1029.2,1029.7
4986,21.10.2014,BadgerysCreek,12.7,56.439795,0.430141,NE,22.0,SW,7.0,86.0,1032.7,1030.4
4987,22.10.2014,BadgerysCreek,12.8,79.469826,0.000000,NNE,33.0,NNW,13.0,57.0,1026.8,1021.0
4988,23.10.2014,BadgerysCreek,10.6,102.824224,0.000000,ESE,33.0,NNW,4.0,77.0,1018.1,1014.7
4989,24.10.2014,BadgerysCreek,15.6,97.958725,0.000000,NNE,35.0,NW,2.0,75.0,1020.2,1013.4
4990,25.10.2014,BadgerysCreek,13.4,107.365357,0.061449,E,31.0,N,4.0,82.0,1015.4,1012.4
4991,26.10.2014,BadgerysCreek,17.7,112.879590,0.000000,E,33.0,WSW,2.0,78.0,1010.5,1006.6
4992,27.10.2014,BadgerysCreek,17.4,105.419157,0.000000,W,80.0,N,7.0,77.0,1008.0,1003.0
4993,28.10.2014,BadgerysCreek,9.5,91.147025,0.000000,WNW,48.0,W,11.0,37.0,1012.4,1008.7
4994,29.10.2014,BadgerysCreek,11.0,85.308426,0.000000,ENE,35.0,SW,13.0,46.0,1017.2,1014.2
4995,31.10.2014,BadgerysCreek,10.5,119.042556,NaN,NaN,NaN,NaN,0.0,55.0,1013.6,1006.6
4996,01.11.2014,BadgerysCreek,18.1,114.501423,0.000000,WNW,70.0,N,17.0,41.0,1003.1,997.7
4997,02.11.2014,BadgerysCreek,10.5,79.145460,1.536217,WSW,46.0,SW,24.0,31.0,1018.3,1016.5
4998,03.11.2014,BadgerysCreek,6.8,75.577427,0.000000,E,39.0,WNW,2.0,56.0,1025.3,1022.2

In [330]:
df = standartization(df, ['MaxTemp', 'Rainfall'])

In [337]:
df = dropNA(df, axis = 'rows', how='any')

In [338]:
from sklearn.model_selection import train_test_split
seed = 7
X_train, X_test, y_train, y_test = train_test_split(np.array(df.Rainfall).reshape(-1,1), np.array(df.MaxTemp).reshape(-1,1), test_size=0.2, random_state=7)

In [ ]:
models = []

#models.append(('LDA', LinearRegression()))

models.append(('CART', DecisionTreeClassifier()))

models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train.astype(int), y_train.astype(int), cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)